# Simple docker-composer.yml
# You can change your port or volume location

version: '3.3'

services:
  syslogger:
    image: syslogger
    container_name: syslogger
    volumes:
      - ./parameter:/parameter
    restart: always
