# Simple docker-composer.yml
# You can change your port or volume location

version: '3.3'

services:
  mqtt2syslogger:
    image: mqtt2syslogger
    container_name: mqtt2syslogger
    volumes:
      - ./parameter:/parameter
    restart: always
